In [2]:
from sqlalchemy import create_engine
from config import db_password
import pandas as pd

In [3]:
db_string = f"postgres://postgres:{db_password}@indusscript.cljludlfcgoa.us-east-2.rds.amazonaws.com:5432/postgres"

In [4]:
engine = create_engine(db_string)

In [5]:
tamildata = pd.read_sql_table('completetamildata', con=engine)
tamildata

,index,form,lemma,upos,xpos,head,FormWithoutLemma,NoSpaceAfter,Counts,formSeparated
0,0,சென்னை,சென்னை,N,NEN-3SN--,2,,0.0,0,"{ச,ெ,ன,்,ன,ை}"
1,1,அருகே,அருகே,P,PP-------,18,,0.0,0,"{அ,ர,ு,க,ே}"
2,2,ஸ்ரீ,ஸ்ரீ,N,NEN-3SN--,4,,0.0,0,"{ஸ,்,ர,ீ}"
3,3,பெரும்புதூரில்,பெரும்புதூர்,N,NEL-3SN--,18,ில்,0.0,136,"{ப,ெ,ர,ு,ம,்,ப,ு,த,ூ,ர,ி,ல,்}"
4,4,கிரீன்,கிரீன்,N,NEN-3SN--,6,,0.0,0,"{க,ி,ர,ீ,ன,்}"
...,...,...,...,...,...,...,...,...,...,...
9576,9576,வேண்டும்,வேண்டு,V,VR-F3SNAA,9,ம்,0.0,144,"{வ,ே,ண,்,ட,ு,ம,்}"
9577,9577,என்பது,என்,T,TQ-------,13,பது,0.0,8,"{எ,ன,்,ப,த,ு}"
9578,9578,தான்,தான்,T,Tq-------,11,,0.0,0,"{த,ா,ன,்}"
9579,9579,அது,அது,R,RpN-3SN--,0,,0.0,0,"{அ,த,ு}"
9580,9580,.,.,Z,Z#-------,0,,0.0,0,{.}

In [11]:
wingdings = ['\u21E6','\u21E7','\u21E8','\u21E9','\u21F3','\u237D','\u2303','\u237D','\u2303','\u2316','\u2324','\u2325',
             '\u2326','\u2327', '\u232B','\u232D','\u238B','\u23F3','\u2423','\u24C5','\u24FF','\u261C','\u261E','\u261D','\u261F','\u25A0','\u25A1','\u2620','\u262F','\u2639','\u263A','\u263C','\u267F','\u26F7','\u2701','\u2702','\u2706','\u2707','\u2708','\u270C','\u270D','\u2744','\u2B00','\u2B01','\u2B02','\u2B03','\u2B04','\u2318','\u2327','\u25C6','\u2605','\u2726','\u2734','\u2735','\u2736','\u2739','\u2756','\u2BD0','\u2BD1','\u272A','\u2730','\u2714']

# Morpheme

In [6]:
morphemelist = pd.read_sql_table('morphemes', con=engine)
morphemelist

    index MorphemeSeparated Morpheme   xpos Regex  Morpheme continued
0       2                 ை        ை  (N.A..S...)                 NaN
1       3         {க,்,க,்}     க்க்  (N.D..S...)                 1.0
2       4         {க,்,க,ு}     க்கு  (N.D..S...)                 NaN
3       5             {க,ு}       கு  (N.D..S...)                 NaN
4       6           {க,ள,ு}      களு  (N.D..P...)                 NaN
..    ...               ...      ...          ...                 ...
92     94               {ை}        ை  (V.A......)                 NaN
93     95             {க,ு}       கு  (V.D......)                 NaN
94     96             {க,்}       க்  (V.D......)                 1.0
95     97           {ா,ல,்}      ால்  (V.I......)                 NaN
96     98           {ி,ல,்}      ில்  (V.L......)                 NaN

[97 rows x 5 columns]

In [14]:
morphemelist['Morpheme'].nunique()

54

In [15]:
morphemetowingdings = morphemelist['Morpheme'].unique()
morphemetowingdings

array(['ை', 'க்க்', 'க்கு', 'கு', 'களு', 'ால்', 'து', 'ின்', 'ில்',
       'ிடம்', 'ோடு', 'ுடன்', 'கள்', 'ேன்', 'கிற', 'ணட', 'க்கிற', 'ன',
       'ீர்கள்', 'ந்த', 'ிய', 'த்த', '்ட', 'த', 'ட்ட', 'க்க', 'க', 'ும்',
       'ா', 'ார்', 'ின', 'வ', 'ோம்', 'ப்ப', 'ர்', 'க்கின்ற', 'ார்கள்',
       'ி', 'கின்ற', 'டு', 'ந்து', 'த்து', 'ட்', 'த்', 'ட்டு', 'ணடு',
       'ணட்', 'ந்த்', 'த்த்', 'ட்ட்', 'வர', 'கள', 'ப', 'க்'], dtype=object)

In [16]:
morphemelist['xpos Regex'].nunique()

31

In [17]:
morphemelist['xpos Regex'].unique()

array(['(N.A..S...)', '(N.D..S...)', '(N.D..P...)', '(N.I......)',
       '(N.G.*)', '(N.L.*)', '(N.S.*)', '(N....P...)', '(V...1S...)',
       '(V...2S...)', '(V.-D3SN.)', '(V..P3SN.)', '(V.-F3SN.)',
       '(V.-T3SN.)', '(V.......N)', '(V...3SH.)', '(V...1P..)',
       '(V...2P..)', '(V..D3PH.)', '(V..P3PH.)', '(V..F3PH.)',
       '(V..T3PH.)', '(V..D3PN.)', '(V..P3PN.)', '(VT.......)',
       '(VW.......)', '(NP.......)', '(V.A......)', '(V.D......)',
       '(V.I......)', '(V.L......)'], dtype=object)

In [18]:
morphemelist[['xpos Regex']]

     xpos Regex
0   (N.A..S...)
1   (N.D..S...)
2   (N.D..S...)
3   (N.D..S...)
4   (N.D..P...)
..          ...
92  (V.A......)
93  (V.D......)
94  (V.D......)
95  (V.I......)
96  (V.L......)

[97 rows x 1 columns]

In [20]:
# wingdings = 
# ['\u21E6','\u21E7','\u21E8','\u21E9','\u21F3',
 
#  '\u237D','\u2303','\u237D','\u2303','\u2316','\u2324','\u2325',
#  '\u2318','\u2327','\u2326','\u2327', '\u232B','\u232D','\u238B','\u23F3',
 
#  '\u2423','\u24C5','\u24FF',

#  '\u25A0','\u25A1', '\u25C6,'
 
#  '\u261C','\u261E','\u261D','\u261F','\u2620','\u262F','\u2639','\u263A',
#  '\u263C','\u267F','\u26F7','\u2605',

#  '\u2701','\u2702','\u2706','\u2707','\u2708','\u270C','\u270D','\u2744',
#  '\u2726','\u2734','\u2735','\u2736','\u2739','\u2756','\u272A','\u2730',
#  '\u2714'

#  '\u2B00','\u2B01','\u2B02','\u2B03','\u2B04',
# '\u2BD0','\u2BD1']
# len(wingdings)

In [24]:
morphemes_df = pd.DataFrame(morphemetowingdings,columns=['Morphemes'])
morphemes_df

   Morphemes
0          ை
1       க்க்
2       க்கு
3         கு
4        களு
5        ால்
6         து
7        ின்
8        ில்
9       ிடம்
10       ோடு
11      ுடன்
12       கள்
13       ேன்
14       கிற
15        ணட
16     க்கிற
17         ன
18    ீர்கள்
19       ந்த
20        ிய
21       த்த
22        ்ட
23         த
24       ட்ட
25       க்க
26         க
27       ும்
28         ா
29       ார்
30        ின
31         வ
32       ோம்
33       ப்ப
34        ர்
35   க்கின்ற
36    ார்கள்
37         ி
38     கின்ற
39        டு
40      ந்து
41      த்து
42        ட்
43        த்
44      ட்டு
45       ணடு
46       ணட்
47      ந்த்
48      த்த்
49      ட்ட்
50        வர
51        கள
52         ப
53        க்

In [22]:
#wingdings list for morphemes
wingdings2 = ['\u2638', '\u2648', '\u2649',  '\u264A', '\u264B', '\u264C', '\u264D', '\u264E', '\u264F', '\u2650', '\u2651', '\u2652', '\u2653', '\u2751', '\u2752', '\u2B27', '\u29EB', '\u2B25', '\u2BB9', '\u25C9', '\u25CE', '\u2BB0', '\u2BB1', '\u2BB2', '\u2BB3', '\u2BB4', '\u2BB5', '\u2BB6', '\u2BB7', '\u2B98', '\u2B9A', '\u2B99', '\u2B9B', '\u2B88', '\u2B8A', '\u2B89', '\u2B8B', '\u25AA', '\u26AA', '\u25FB', '\u27E1', '\u2311', '\u2BD1', '\u24EA', '\u2460', '\u2461', '\u2462', '\u2463', '\u2464', '\u2465', '\u2466', '\u2467', '\u2468', '\u2469', '\u24FF', '\u2776', '\u2777', '\u2778', '\u2779', '\u277A', '\u277B', '\u277C', '\u277D', '\u277E', '\u277F']
len(wingdings2)

65

In [23]:
wingdings_df = pd.DataFrame(wingdings2,columns=['Wingdings'])
wingdings_df

   Wingdings
0          ☸
1          ♈
2          ♉
3          ♊
4          ♋
..       ...
60         ❻
61         ❼
62         ❽
63         ❾
64         ❿

[65 rows x 1 columns]

In [27]:
columns = ['Morphemes','Wingdings']
morphemes_logo = pd.DataFrame(columns = columns)
morphemes_logo['Morphemes'] = morphemes_df['Morphemes']
morphemes_logo['Wingdings'] = wingdings_df['Wingdings']
morphemes_logo

   Morphemes Wingdings
0          ை         ☸
1       க்க்         ♈
2       க்கு         ♉
3         கு         ♊
4        களு         ♋
5        ால்         ♌
6         து         ♍
7        ின்         ♎
8        ில்         ♏
9       ிடம்         ♐
10       ோடு         ♑
11      ுடன்         ♒
12       கள்         ♓
13       ேன்         ❑
14       கிற         ❒
15        ணட         ⬧
16     க்கிற         ⧫
17         ன         ⬥
18    ீர்கள்         ⮹
19       ந்த         ◉
20        ிய         ◎
21       த்த         ⮰
22        ்ட         ⮱
23         த         ⮲
24       ட்ட         ⮳
25       க்க         ⮴
26         க         ⮵
27       ும்         ⮶
28         ா         ⮷
29       ார்         ⮘
30        ின         ⮚
31         வ         ⮙
32       ோம்         ⮛
33       ப்ப         ⮈
34        ர்         ⮊
35   க்கின்ற         ⮉
36    ார்கள்         ⮋
37         ி         ▪
38     கின்ற         ⚪
39        டு         ◻
40      ந்து         ⟡
41      த்து         ⌑
42        ட்         ⯑
43        த்         ⓪
44      ட்டு         ①
45       ணடு         ②
46       ணட்         ③
47      ந்த்         ④
48      த்த்         ⑤
49      ட்ட்         ⑥
50        வர         ⑦
51        கள         ⑧
52         ப         ⑨
53        க்         ⑩

In [ ]:
# Create function (takes in array of words and replaces with converted wingdings array)
# Case: morpheme = form
def morpheme_to_wingding(input):
    morpheme = morpheme_logo['Morphemes']
    logo = morpheme_logo['Wingdings']
    # for every word in array, compare to clitics_logo
    for j in range(len(input)):
        for i in range(len(morpheme_logo)):
            if input[j] == morpheme[i]:
                input[j] = logo[i];
    return input

In [11]:
# Example Case: morpheme = end of form
# E.g. Noun Accusative Singular Case
#re = '(N.A..S...)'
#morphemelist[morphemelist['xpos Regex'].str.contains(rf'{re}')]
# if form = 'தமிழகத்தை' and morpheme = 'ததை'
count = 0
for j in range(len(morpheme)):
    if word[-j] == morpheme[-j]:
        count++;
if count = len(morpheme):
    word = morpheme

   index MorphemeSeparated Morpheme   xpos Regex  Morpheme continued
0      2                 ை        ை  (N.A..S...)                 NaN